### ISSUE TITLE
[BUG/ERROR]mp klemmas not working

### ISSUE THREAD

**Issue by anziw** [forrestdavis/NLPScholar#7]
## Describe the bug

When I run MinimalPair experiment under analyze mode, the result files will always include all the lemmas no matter what value I set "k_lemmas" to. 

## To Reproduce

1. Reset directories in "config.yaml"
2. Run main.py
3. Go to wherever results file should be generated
4. Scroll down and see error

## Expected behavior

Only seeing |k| lemmas in the result files.

## Observed behavior 

Results of all lemmas as if k_lemmas value was set to default ("all").

## Screenshots 

PFA files I used and generated

## Setup (please complete the following information)
 - OS: iOS

## Additional context

NA
[issue.zip](https://github.com/user-attachments/files/17300065/issue.zip)

**Comment by grushaprasad** [comment]
Fixed with commit [e569f79](https://github.com/forrestdavis/NLPScholar/commit/e569f79ae9448b0409abc86b325eac21169a3504). Previous version was computing the correct final result, but storing incorrect interim file. If you run it with k_lemmas = 1 you get an interim file with 40 rows (1 topk lemma for every contextid; 2 rows per lemma for expected and unexpected version).
